main/urls.py
from django.urls import path
from main.views import show_main, create_todo, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user, edit_todo, delete_todo

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-todo', create_todo, name='create_todo'),    
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-todo/<int:id>', edit_todo, name='edit_todo'),
    path('delete/<int:id>', delete_todo, name='delete_todo')
]

todo_tracker/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),    
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    deadline = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Todo

class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ["name", "deadline", "description"]

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from main.forms import TodoForm
from main.models import Todo

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    todos = Todo.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'PBP A',
        'todos': todos,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_todo(request):
    form = TodoForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        todo = form.save(commit=False)
        todo.user = request.user
        todo.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_todo.html", context)

def edit_todo(request, id):
    # Get todo berdasarkan ID
    todo = Todo.objects.get(pk = id)

    # Set todo sebagai instance dari form
    form = TodoForm(request.POST or None, instance=todo)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_todo.html", context)

def delete_todo(request, id):
    # Get data berdasarkan ID
    todo = Todo.objects.get(pk = id)
    # Hapus data
    todo.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def show_xml(request):
    data = Todo.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Todo.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Todo.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Todo.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

main/templates/create_todo.html
{% extends 'base.html' %} {% block content %}
<h1>Add New Todo</h1>

<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td></td>
      <td>
        <input type="submit" value="Add Todo" />
      </td>
    </tr>
  </table>
</form>

{% endblock %}

main/templates/edit_todo.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Todo</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Todo"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %} 

{% block content %}
<div class="login">
  <h1>Login</h1>

  <form method="POST" action="">
    {% csrf_token %}
    <table>
      <tr>
        <td>Username:</td>
        <td>
          <input
            type="text"
            name="username"
            placeholder="Username"
            class="form-control"
          />
        </td>
      </tr>

      <tr>
        <td>Password:</td>
        <td>
          <input
            type="password"
            name="password"
            placeholder="Password"
            class="form-control"
          />
        </td>
      </tr>

      <tr>
        <td></td>
        <td><input class="btn login_btn" type="submit" value="Login" /></td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %} Don't have an account yet?
  <a href="{% url 'main:register' %}">Register Now</a>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %} {% block content %}
<h1>Todo Tracker Page</h1>

<h5>Name:</h5>
<p>{{name}}</p>

<h5>Class:</h5>
<p>{{class}}</p>

<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for todo in todos %}
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{todo.name}}</h5>
        <p class="card-text">{{todo.description}}</p>
        <p class="card-text"><small class="text-body-secondary">{{todo.deadline}}</small></p>
        <a href="{% url 'main:edit_todo' todo.pk %}" class="btn btn-warning">Edit</a>
        <a href="{% url 'main:delete_todo' todo.pk %}" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
  
<br />

<a href="{% url 'main:create_todo' %}">
  <button>Add New Todo</button>
</a>

<a href="{% url 'main:logout' %}">
  <button>Logout</button>
</a>

<h5>Sesi terakhir login: {{ last_login }}</h5>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %} 

{% block meta %}
<title>Register</title>
{% endblock meta %} 

{% block content %}

<div class="login">
  <h1>Register</h1>

  <form method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td><input type="submit" name="submit" value="Daftar" /></td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %}
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% endblock meta %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
  </head>

  <body class="container">
    {% block content %} {% endblock content %}
  </body>
</html>